spring:
  profiles:
    include:
    - "h2db" #원하는 profile 활성화 시키기
    - "default"
---
spring:
  config:
    activate:
      on-profile: "default"
  application:
    name: "moamoa"

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: Google
            client-id: 116936982957-9freqspkmug2q0cvsdtu8tgel51eki22.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://localhost:9000/login/oauth2/code/google #서비스에 등록한 우리쪽 로그인 성공 URI
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
          naver:
            client-name: Naver
            client-id: 6Bx7WGCXaCEqqWvzQL0U
            client-secret: xc8lO61rKM
            redirect-uri: https://localhost:9000/login/oauth2/code/naver #서비스에 등록한 우리쪽 로그인 성공 URI
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - ageGroup #연령대
          kakao:
            client-name: Kakao
            client-id: 6e3faaf54c3bb54edc4f1045269112d5
            client-secret: H4NeULLRy73YdSUcGfJPDlySIEoSl5ga
            redirect-uri: https://localhost:9000/login/oauth2/code/naver #서비스에 등록한 우리쪽 로그인 성공 URI
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize #서비스 로그인 창 주소
            token-uri: https://nid.naver.com/oauth2.0/token #토큰 발급 서버 주소
            user-info-uri: https://openapi.naver.com/v1/nid/me #사용자 정보 획득 주소
            user-name-attribute: response #응답 데이터 변수
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, ka


jwt:
  secret: b0e36a1dda45e3193143c586be97cd26a6af7d647de442d16809c4f6464f31329017c965cf43579460b3622ee90afd053d930f32f2491457deb26bd037160f68
  accessTokenExpiration: 86400000 # 1일
server:
  port: 9000
---
spring:
  config:
    activate:
      on-profile: "h2db"
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test;mode=mysql  # inmemory mode실행 및 mysql 모드로 실행
#    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1; mode=mysql
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: h2  # 알아서 해줘서 해줄 필요 없긴 함
    hibernate:
      ddl-auto: create-drop # 매 실행시 db create & 서버 종료시 db drop
    show-sql: true

