spring:
  profiles:
    include:
    - "h2db" #원하는 profile 활성화 시키기
    - "default"
---
spring:
  config:
    activate:
      on-profile: "default"
  application:
    name: "moamoa"
server:
  port: 9000
---
spring:
  config:
    activate:
      on-profile: "h2db"
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test;mode=mysql  # inmemory mode실행 및 mysql 모드로 실행
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: h2  # 알아서 해줘서 해줄 필요 없긴 함
    hibernate:
      ddl-auto: create-drop # 매 실행시 db create & 서버 종료시 db drop
    show-sql: true