name: Java CI with Gradle  # Name to be shown

on:  # Event to trigger this workflow
  pull_request:
    branches: [ main, dev ]

jobs:  # 할 일
  build:
    runs-on: ubuntu-latest  # 어느 환경에서 빌드 할꺼니
    permissions:  # permissions about GITHUB_TOKEN
      read-all
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK  #build를 위한 jdk seting
        uses: actions/setup-java@v4.6.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.5'  # 기본 설정을 못 찾겠다. https://github.com/gradle/actions

      - name: Build with Gradle
        # env:
          # MYSQL_URL: ${{ secrets.MYSQL_URL }}
          # MYSQL_USER: ${{ secrets.MYSQL_USER }}
          # MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

          # ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          # SECRET_KEY: ${{ secrets.SECRET_KEY }}
          # REGION: ${{ secrets.REGION }}
        run: ./gradlew build

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: '**/build/test-results/test/TEST-*.xml'

  dependency-submission:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
